name: MasterDeployCI
on:
  push:
    branches:
      - master
      - 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      env:
        DEPLOY_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      run: npm run deploy
    - name: Updating Domain
      run: echo "Domain updated"
