name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      env: 
        PERSONAL_DEPLOY_ACCESS_TOKEN: ${{ secrets.PERSONAL_DEPLOY_ACCESS_TOKEN }}
      run: |
        git config user.email "ela.ri.bag@gmail.com"
        git config user.name "GabrielaSaldana"
        git remote set-url origin https://${PERSONAL_DEPLOY_ACCESS_TOKEN}@github.com/GabrielaSaldana/profile.git
        npm run deploy
    - name: Updating Domain
      run: echo "Domain updated"
