name: Node.js CI MasterDeployCI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "ela.ri.bag@gmail.com"
        git config --global user.name "GabrielaSaldana"
        git remote set-url origin https://c278ebb341e0e711bb6e0eb8d2ad6a7a7a12c20a@github.com/GabrielaSaldana/profile.git
        npm run deploy
    - name: Updating Domain
      run: echo "Update domain"
      env:
        CI: true
